require:
- rubocop-performance
- rubocop-rake
- rubocop-rspec

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.1

Gemspec/DevelopmentDependencies:
  Enabled: false

Layout/ArgumentAlignment:
  EnforcedStyle: with_fixed_indentation
Layout/ClosingHeredocIndentation:
  Enabled: false
Layout/LineEndStringConcatenationIndentation:
  EnforcedStyle: indented
Layout/LineLength:
  Enabled: false
Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented
Layout/MultilineOperationIndentation:
  EnforcedStyle: indented

Metrics:
  Enabled: false

Naming/AccessorMethodName:
  Enabled: false
Naming/HeredocDelimiterNaming:
  Enabled: false
Naming/RescuedExceptionsVariableName:
  PreferredName: error

RSpec/BeEq:
  Enabled: false
RSpec/ContextWording:
  Enabled: false
RSpec/DescribedClass:
  Enabled: false
RSpec/ExampleLength:
  Enabled: false
RSpec/MultipleExpectations:
  Enabled: false

Style/Documentation:
  Enabled: false
Style/FetchEnvVar:
  Enabled: false
Style/StringLiterals:
  EnforcedStyle: double_quotes
Style/SymbolArray:
  EnforcedStyle: brackets
Style/WordArray:
  EnforcedStyle: brackets
