# This should always correspond to the earliest non-EOL Ruby version.
AllCops:
  TargetRubyVersion: 2.2

# TODO: Re-enable this cop after TomDoc code deocumentation is added.
Style/Documentation:
  Enabled: false

# Allow some style changes in the specs.
Metrics/BlockLength:
  Exclude:
    - spec/**/*
Metrics/LineLength:
  Exclude:
    - spec/**/*
Metrics/ModuleLength:
  Exclude:
    - spec/**/*
Style/BracesAroundHashParameters:
  Exclude:
    - spec/**/*

# These style conventions are personal preference.
Layout/AlignHash:
  EnforcedLastArgumentHashStyle: ignore_implicit
Layout/AlignParameters:
  EnforcedStyle: with_fixed_indentation
Layout/IndentHash:
  EnforcedStyle: consistent
Layout/IndentHeredoc:
  Enabled: false
Naming/HeredocDelimiterNaming:
  Enabled: false
Style/DoubleNegation:
  Enabled: false
Style/StringLiterals:
  EnforcedStyle: double_quotes
Style/SymbolArray:
  EnforcedStyle: brackets
Style/WordArray:
  EnforcedStyle: brackets
